### ISSUE TITLE
Please advertise the fact it won't properly work cross-frame

### ISSUE THREAD

**Issue by kapouer** [todojs/esequal#2]
Because `instanceof Stuff` is actually `instanceof window.Stuff` and two different frames won't have same prototypes objects, as explained in https://groups.google.com/forum/#!msg/comp.lang.javascript/XTWYCOwC96I/70rNoQ3L-xoJ

I just got bitten by basically `equal([], []) == false` which made learn javascript the hard way.

**Comment by todojs** [comment]
The solution is simple with esequal, you can use:

`equal(arrayFromThisFrame, arrayFromOtherFrame, {nonStrict: true});`

Kind regards
